### ISSUE TITLE
[Problem] Maximum recursion depth exception in assembly

### ISSUE THREAD

**Issue by johnsonm** [Ondsel-Development/FreeCAD#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have created an assembly of parts that were initially created in FreeCAD 0.22.dev FreeCAD_weekly-builds-35966-2024-02-14-conda-Linux-x86_64-py310.AppImage using what I think is a parsimonious set of constraints, which as far as I can tell are not recursive in structure. I created it by a process of importing and grounding one part, then a cycle of importing one new part and constraining it to existing parts already constrained until I had imported all the parts. This process ought to avoid cycles, and in reviewing the Joint objects I have not noticed a cycle.

However, even loading the assembly I get this error:

```
<class 'RecursionError'>: maximum recursion depth exceeded in comparison
Traceback (most recent call last):
  File "/tmp/.mount_OndselNI856W/usr/Mod/Assembly/JointObject.py", line 777, in updateData
    self.set_JCS_placement(self.transform2, plc, joint.Object2, joint.Part2)
  File "/tmp/.mount_OndselNI856W/usr/Mod/Assembly/JointObject.py", line 751, in set_JCS_placement
    global_plc = UtilsAssembly.getGlobalPlacement(obj, part)
  File "/tmp/.mount_OndselNI856W/usr/Mod/Assembly/UtilsAssembly.py", line 290, in getGlobalPlacement
    foundPlacement = getTargetPlacementRelativeTo(
  File "/tmp/.mount_OndselNI856W/usr/Mod/Assembly/UtilsAssembly.py", line 324, in getTargetPlacementRelativeTo
    foundPlacement = getTargetPlacementRelativeTo(
  File "/tmp/.mount_OndselNI856W/usr/Mod/Assembly/UtilsAssembly.py", line 324, in getTargetPlacementRelativeTo
    foundPlacement = getTargetPlacementRelativeTo(
  File "/tmp/.mount_OndselNI856W/usr/Mod/Assembly/UtilsAssembly.py", line 350, in getTargetPlacementRelativeTo
    foundPlacement = getTargetPlacementRelativeTo(
  File "/tmp/.mount_OndselNI856W/usr/Mod/Assembly/UtilsAssembly.py", line 350, in getTargetPlacementRelativeTo
    foundPlacement = getTargetPlacementRelativeTo(
  File "/tmp/.mount_OndselNI856W/usr/Mod/Assembly/UtilsAssembly.py", line 350, in getTargetPlacementRelativeTo
    foundPlacement = getTargetPlacementRelativeTo(
  [Previous line repeated 991 more times]
  File "/tmp/.mount_OndselNI856W/usr/Mod/Assembly/UtilsAssembly.py", line 311, in getTargetPlacementRelativeTo
    if targetObj == part and inContainerBranch and not ignorePlacement:
<class 'RecursionError'>: maximum recursion depth exceeded in comparison
```

If I have inadvertently created a recursive set of constraints, it would be helpful to have an error message that would highlight the graph cycles. For example, if I saw something like "Constraint cycle detected: Part A : Joint B : Part C : Joint D : Part E : Joint F : Part A" I would know where to start looking.

I tried to upload the files as a zip containing the two FCStd files, but github would not accept them, and also didn't show me an error. So they are available for download from here instead:

https://gitlab.com/mcdanlj/RotaryBroach/-/commit/f05ee0ec66c513e92cb3ec68c2de4d3c5fe70b35

### Full version info

```shell
OS: Fedora Linux 39 (Workstation Edition) (GNOME/gnome)
Word size of Ondsel: 64-bit
Version: 2024.1.0.35694 (Git) AppImage
Build type: Release
Branch: flavor
Hash: b070090c6873b3fcf4be9a459219d22edfc4e7cf
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Ondsel-Lens 2024.1.22.01
  * OpenDark 2023.12.17
```
```


### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnsonm** [comment]
This appears to be resolved in upstream FreeCAD_weekly-builds-36228-2024-03-01-conda-Linux-x86_64-py310.AppImage
